# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v_vid_in_axi4s_0 || ORIG_REF_NAME==v_vid_in_axi4s_0}]

# XDC: ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v_vid_in_axi4s_0 || ORIG_REF_NAME==v_vid_in_axi4s_0}] {/inst }]/inst ]]
